### ISSUE TITLE
Repo configuration guide

### ISSUE THREAD

**Issue by mattmills097** [finos-labs/gaad-hackathon-template#11]
We need to create the basic guidance for preparing a project workspace.

1. Develop the [configuration guide](https://github.com/vinomaster/gaad-hackathon-template/blob/main/submission-guides/configuration-instructions.md)

- Do we need the /code folder?

- We need to test the options for Visual Collab Tools ; need to make sure sharing with judges is accessible.

2. All steps must be tested

**Comment by vinomaster** [comment]
Complete; Structure provided to Axa pending their PR.
