### ISSUE TITLE
Design Thinking Guide

### ISSUE THREAD

**Issue by mattmills097** [finos-labs/gaad-hackathon-template#12]
We need to create the basic guidance for preparing and submitting a DT Track project.

* Develop the [design thinking artifacts guide](https://github.com/finos-labs/gaad-hackathon-template/blob/main/submission-guides/design-thinking-artifacts.md)
- [x]   Develop the Mural Board for the Theme Builder
- [x]   Details for Plenary Sessions from participant Guide
- [x]   Sample user Story
- [x]   Sample materials
- [x]   Confirm Exit Critera
- [x]    PowerPoint Playback Brief

**Comment by mattmills097** [comment]
- [x] Instructions for how to use Design Thinking recipe in Mural
- [x] Instructions for how to leverage output from recipe into playback brief

**Comment by mattmills097** [comment]
All changes are reflected via this PR: https://github.com/finos-labs/gaad-hackathon-template/pull/15

@vinomaster

**Comment by vinomaster** [comment]
@mdacic01 @mattmills097  Please update the DT Guide to point to our sample Board in Action to reflect a how to do example.

**Comment by mattmills097** [comment]
sample DT board added to DT guide in this PR: https://github.com/finos-labs/gaad-hackathon-template/pull/21
