### ISSUE TITLE
Migrate playback deck template to github

### ISSUE THREAD

**Issue by vinomaster** [finos-labs/gaad-hackathon-template#5]
## Problem
Currently we have copies of playback deck template in [Google docs](https://docs.google.com/presentation/d/1rZGvHs2P7DAQhsuU2DDylQQgRlUjdXpD9EbKw3yxOpc) and [GitHub](https://github.com/finos-labs/gaad-hackathon-template/tree/main/challenges/common/presentations). The objective of the hackers template is to maintain a single source of truth for latest and greatest submission assets.

## Solution
1. Finalize latest Google docs version.
2. Export new PPT version from Google Docs into [GitHub](https://github.com/finos-labs/gaad-hackathon-template/tree/main/challenges/common/presentations).
3. All future maintenance to template **must** be in Github PPT file. 
4. Update this [README]([GitHub](https://github.com/finos-labs/gaad-hackathon-template/tree/main/challenges/common/presentations)  to remove all mention of Google Docs. 
5. Update the [DT Submission Guide](https://github.com/finos-labs/gaad-hackathon-template/blob/main/submission-guides/design-thinking-artifacts.md) to remove all mention of Google Docs.

**Comment by vinomaster** [comment]
Fix missing Mural links [here](https://github.com/finos-labs/gaad-hackathon-template/blob/main/submission-guides/design-thinking-artifacts.md#sample-material).

**Comment by vinomaster** [comment]
Please read and update/fix [this section](https://github.com/finos-labs/gaad-hackathon-template/blob/main/submission-guides/design-thinking-artifacts.md#design-thinking-day-assets) as it is derived from old TruCreds content.

**Comment by mattmills097** [comment]
PR: https://github.com/finos-labs/gaad-hackathon-template/pull/6 @vinomaster

**Comment by mattmills097** [comment]
FYI: Mural links will not be ready until we finalize the recipe.

**Comment by vinomaster** [comment]
Mural links complete!
