### ISSUE TITLE
Challenge 2 Details

### ISSUE THREAD

**Issue by vinomaster** [finos-labs/gaad-hackathon-template#9]
1. AXA needs to provide details in [setup.md](https://github.com/finos-labs/gaad-hackathon-template/blob/main/challenges/challenge2/setup.md) to outline their challenge requirements and track details.

**Comment by vinomaster** [comment]
@ana-gamito @ricardsoleaxa Please use this issue for your PRs

**Comment by ana-gamito** [comment]
Created a PR with some changes to add --> #22 
Thank you in advance!
